## Introduction

This repository corresponds to the paper titled "Volatile organic compound source apportionment in a fenceline community following THRIVEair, a community-responsive air monitoring network." You can learn more about THRIVEair at: https://thriveairphilly.com/

### Abstract

**Background:** Urban exposure to volatile organic compounds (VOCs) is associated with a wide range of adverse health outcomes, including cancers and respiratory outcomes. We previously partnered with Philly Thrive, a Philadelphia-based environmental justice organization, to co-design a one-year VOC monitoring campaign in South and Southwest Philadelphia. Our goal was to quantify air quality impacts of traffic and local redevelopment of a former oil refinery site. Though our community-focused research dissemination focused on benzene, a primary pollutant of concern, we also characterized many additional VOCs. Here, we present source identification and apportionment using diagnostic ratios, principal component analysis (PCA), and positive matrix factorization (PMF).

**Methods:** Using passive thermal desorption tubes, we took one-week integrated samples of 38 VOCs across 20 monitoring sites from July 2023 – June 2024. We summarized concentrations of VOCs across land use types and traffic density. To identify potential sources, we calculated the toluene:benzene (T/B) ratio and *(m,p)*-xylenes:ethylbenzene (X/E) ratios and compared them across sites. We employed PCA and PMF to identify potential VOC sources.

**Results:** Generally, VOC concentrations were generally higher in industrial, vs. non-industrial, and high-traffic, vs. low-traffic areas. Benzene, of community concern, was generally found in lower concentrations (mean 1.32 µg/m³; range: 0.30-9.04 µg/m^3^) than during active refinery operations. We identified (*m,p*)-xylenes as a potential pollutant of concern, with high concentrations particularly among industrial sites. T/B and X/E ratios were higher among industrial and high-traffic sites, indicating fresh emissions of benzene derivatives. PCA and PMF revealed five VOC sources: (1) vehicular exhaust, (2) petroleum-based solvents, (3) gasoline evaporation, (4) background / legacy contamination, and (5) auto repair industry.

**Significance:** Using a community-responsive study design, we characterized 38 VOCs in ambient air in a pollution-burdened area of South Philadelphia.  Source apportionment analyses confirmed traffic as a primary VOC source in the area, echoing community concern, and further identified industrial solvent use and legacy air pollution as contributors to VOC pollution

## File Structure

### Directory Tree

```         
.
├── data
│   ├── codebook.xlsx 
│   ├── site_info.csv 
│   ├── raw
│   ├── clean 
│   └── shp <--- shapefiles for mapping parcels
├── R (see details table below)
│   ├── 00_plot_theme.R
│   ├── 01_prepare_site_info.R
│   ├── 02_prepare_data.R
│   ├── 03_summarize_data.R
│   ├── 04_btex_ratios.R
│   ├── 05_run_pca.R
│   └── 05_summarize_pca_pmf_results.R
├── results
│   ├── tables 
│   ├── figures 
│   ├── supplemental 
│       ├── tables 
│       └── figures 
│   └── interim_results 
│       ├── figures 
│       ├── tables
│       ├── pmf_results 
│       └── pca_results 
├── thriveair_analysis.Rproj
└── README.md
```

### Code Details

| Folder | File Name | Details |
|------------------------|------------------------|------------------------|
| R | 00_plot_theme | Create basemap and ggplot theme to be sourced in all other code dealing with mapping and/or visualization. |
| R | 01_prepare_site_info | Clean and prepare site information. |
| R | 02_clean_data | Clean raw data, link data to site information and source classes. |
| R | 03_summarize_data | Summary statistics, distribution plots, and reliability calculations |
| R | 04_btex_ratios | BTEX ratio analysis an visualization |
| R | 05_run_pca | Principal component analysis (PCA), primary analysis and sensitivity analyses. Saves interim results. |
| R | 06_summarize_pca_pmf_results | Tabulate, plot, and map PCA and PMF results. |

## Contact & Links

**Contact:**\
Lisa Frueh \| [lfrueh.com](https://lfrueh.com) \| lf649 at drexel.edu
Lisa Frueh | [lfrueh.com](https://lfrueh.com) | lf649@drexel.edu

**Project Link:**\
https://github.com/lfrueh/thriveair_analysis

**More About THRIVEair:**\
https://thriveairphilly.com/

**Interactive data dashboard:**\
https://lisa-frueh.shinyapps.io/THRIVEair_results/

